### ISSUE TITLE
The firestore sample is very old and appears to be broken

### ISSUE THREAD

**Issue by JustinBeckwith** [GoogleCloudPlatform/grpc-gcp-node#129]
Should we delete this sample?
https://github.com/GoogleCloudPlatform/grpc-gcp-node/tree/master/firestore/examples/end2end

Taking a look I see that:
- the dependencies are years out of date
- the instructions in the README don't work
- the linter isn't configured to fix these files, and there are hundreds of issues
- there are no tests
- there are no license headers

I am having a hard time believing that these are useful, and I'd like to delete them.  Thoughts?

**Comment by stanley-cheung** [comment]
Ok with me. More cleanup the merrier!
