### ISSUE TITLE
support grpc-js

### ISSUE THREAD

**Issue by alexander-fenster** [GoogleCloudPlatform/grpc-gcp-node#41]
Creating this issue for tracking purposes.

Since we (client libraries) are planning to move from `grpc` to `@grpc/grpc-js`, `grpc-gcp` must start supporting `@grpc/grpc-js`. @WeiranFang this is likely for you :)

**Comment by WeiranFang** [comment]
Thanks. I will work on this once we have the new package `@types/grpc`. Link to proposal for this new package: https://github.com/grpc/proposal/pull/126

**Comment by JustinBeckwith** [comment]
Just to give priority - this is going to block us from using grpc-js in the spanner library.  This is kinda P1-ish.

**Comment by WeiranFang** [comment]
@murgatroid99  do we have a timeline on `@types/grpc`?

**Comment by WeiranFang** [comment]
This is currently blocked by the client interceptors implementation in `grpc-js`: https://github.com/grpc/grpc-node/pull/1184

**Comment by WeiranFang** [comment]
@alexander-fenster grpc-gcp (new release v0.3.0) is now supporting grpc-js.
